services:
  secretinference:
    image: ghcr.io/mrgarbonzo/secretinference@sha256:578e7ecc50dd8b6be313401ca197fed4571ac0b140b93ef5ea8ef747a2d5f17d
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PAYMENT_ADDRESS=${PAYMENT_ADDRESS}
      - NETWORK=${NETWORK:-base-sepolia}
      - PORT=3000
      - HOST=0.0.0.0
      - ATTESTATION_ENDPOINT=https://172.17.0.1:29343/cpu
      - SECRETVM_AGENT_PRIVATE_KEY=${SECRETVM_AGENT_PRIVATE_KEY}
      - SECRETVM_VM_ID=${SECRETVM_VM_ID}
      - DISABLE_PAYMENT=${DISABLE_PAYMENT}
      - ALLOWED_PROVIDERS=${ALLOWED_PROVIDERS}
